env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - standard
parserOptions:
  ecmaVersion: 12
rules:
  arrow-parens:
    - warn
    - as-needed
  semi: 0
  space-before-function-paren: 0
  eol-last: 0
  no-tabs: 0
  indent: 0
